# Generated by Django 5.0.1 on 2024-02-14 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aisettings",
            old_name="profile_id",
            new_name="other_profile_id",
        ),
    ]
