# Generated by Django 5.0.1 on 2024-02-14 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flat_applications", "0003_rename_profile_id_lazyrenter_lazy_profile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazyrenter",
            name="lazy_profile_id",
        ),
        migrations.DeleteModel(
            name="LazyFlatApplication",
        ),
        migrations.DeleteModel(
            name="LazyRenter",
        ),
    ]
