# Generated by Django 5.0.1 on 2024-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flat_applications",
            "0006_rename_landlord_mail_landlord_landlord_contact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="landlord",
            name="landlord_phone",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="lazyrenter",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="lazyrenter",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
