# Generated by Django 5.0.1 on 2024-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flat_applications",
            "0007_landlord_landlord_phone_alter_lazyrenter_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lazyflatapplication",
            name="flat_application_costs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="landlord_contact",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
