# Generated by Django 5.0.1 on 2024-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flat_applications",
            "0008_lazyflatapplication_flat_application_costs_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyflatapplication",
            name="postal_code",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lazyflatapplication",
            name="rooms",
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
    ]
