# Generated by Django 5.0.1 on 2024-02-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=60)),
                ("company_website", models.URLField(blank=True, max_length=250)),
                ("company_address", models.CharField(blank=True, max_length=60)),
                ("company_mail", models.EmailField(blank=True, max_length=60)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos"),
                ),
                ("company_info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LazyJobApplication",
            fields=[
                (
                    "lazy_application_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("add_link", models.URLField(max_length=250)),
                ("job_title", models.CharField(max_length=60)),
                ("job_ad_text", models.TextField()),
                ("recruiter_name", models.CharField(blank=True, max_length=60)),
                ("recruiter_mail", models.EmailField(blank=True, max_length=60)),
                ("recruiter_phone", models.CharField(blank=True, max_length=60)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Time"),
                            ("part", "Part Time"),
                            ("intern", "Internship"),
                            ("free", "Freelance"),
                            ("temp", "Temporary"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("salary_expectation", models.IntegerField(blank=True, null=True)),
                (
                    "to_highlight",
                    models.TextField(
                        blank=True,
                        verbose_name="Anything to highlight apart from CV Info?",
                    ),
                ),
                ("application_send_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("apply", "Need to apply"),
                            ("applied", "Applied"),
                            ("interview", "Interview"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="apply",
                        max_length=20,
                    ),
                ),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("salary_offer", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("application_costs", models.FloatField(blank=True, null=True)),
                (
                    "ai_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.aisettings",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_applications.company",
                    ),
                ),
            ],
        ),
    ]
