# Generated by Django 5.0.1 on 2024-02-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=60,
                    ),
                ),
            ],
        ),
    ]
