# Generated by Django 5.0.1 on 2024-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0003_remove_lazyjobapplication_ai_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="company_address",
            new_name="company_location",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_logo",
        ),
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="job_title",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Time"),
                    ("part", "Part Time"),
                    ("intern", "Internship"),
                    ("free", "Freelance"),
                    ("temp", "Temporary"),
                ],
                default="full",
                max_length=60,
            ),
        ),
    ]
# Generated by Django 4.2.10 on 2024-02-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0003_remove_lazyjobapplication_ai_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address',
            new_name='company_location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.AlterField(
            model_name='lazyjobapplication',
            name='job_type',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('intern', 'Internship'), ('free', 'Freelance'), ('temp', 'Temporary')], max_length=50),
        ),
    ]
