# Generated by Django 5.0.1 on 2024-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0005_alter_lazyjobapplication_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazyjobapplication",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
    ]
