# Generated by Django 5.0.1 on 2024-02-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0009_alter_lazyjobapplication_profile_id"),
        ("users", "0008_alter_lazyuserprofile_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="job_applications.company",
            ),
        ),
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lazyuserprofile"
            ),
        ),
    ]
