# Generated by Django 5.0.1 on 2024-02-14 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_profile_id_aisettings_other_profile_id"),
        ("job_applications", "0003_remove_lazyjobapplication_ai_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AiSettings",
        ),
    ]
