# Generated by Django 5.0.1 on 2024-02-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_lazyuserprofile_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyuserprofile",
            name="availability",
            field=models.DateField(verbose_name="Earliest Start Date"),
        ),
    ]
