# Generated by Django 5.0.1 on 2024-02-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landlord",
            fields=[
                ("landlord_id", models.AutoField(primary_key=True, serialize=False)),
                ("landlord_name", models.CharField(max_length=60)),
                ("landlord_mail", models.EmailField(blank=True, max_length=60)),
                ("landlord_phone", models.CharField(blank=True, max_length=60)),
                ("landlord_address", models.TextField()),
                (
                    "landlord_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("company", "Company"),
                            ("agent", "Agent"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("landlord_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LazyRenter",
            fields=[
                ("renter_id", models.AutoField(primary_key=True, serialize=False)),
                ("renter_mail", models.EmailField(blank=True, max_length=60)),
                ("renter_phone", models.CharField(blank=True, max_length=60)),
                ("renter_address", models.TextField(blank=True)),
                (
                    "no_of_people",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of People to move"
                    ),
                ),
                (
                    "children",
                    models.IntegerField(default=False, verbose_name="No. of children"),
                ),
                (
                    "net_income",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Net Income per month"
                    ),
                ),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("pets", models.BooleanField(default=False, verbose_name="Pets")),
                ("type_of_pets", models.CharField(blank=True, max_length=60)),
                (
                    "mention_pets",
                    models.BooleanField(default=False, verbose_name="Mention Pets"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LazyFlatApplication",
            fields=[
                (
                    "flat_application_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("flat_ad_link", models.URLField(max_length=300)),
                (
                    "landlord_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flat_applications.landlord",
                    ),
                ),
            ],
        ),
    ]
