# Generated by Django 5.0.1 on 2024-02-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flat_applications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazyrenter",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lazyuserprofile"
            ),
        ),
        migrations.AddField(
            model_name="lazyflatapplication",
            name="renter_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="flat_applications.lazyrenter",
            ),
        ),
    ]
