# Generated by Django 5.0.1 on 2024-02-14 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flat_applications", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lazyrenter",
            old_name="profile_id",
            new_name="lazy_profile_id",
        ),
    ]
