# Generated by Django 5.0.1 on 2024-03-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flat_applications", "0005_alter_landlord_landlord_type"),
        ("users", "0008_alter_lazyuserprofile_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landlord",
            old_name="landlord_mail",
            new_name="landlord_contact",
        ),
        migrations.RemoveField(
            model_name="landlord",
            name="landlord_phone",
        ),
        migrations.RemoveField(
            model_name="landlord",
            name="landlord_type",
        ),
        migrations.AlterField(
            model_name="landlord",
            name="landlord_address",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="landlord_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name="LazyRenter",
            fields=[
                ("renter_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("renter_mail", models.EmailField(blank=True, max_length=60)),
                ("renter_phone", models.CharField(blank=True, max_length=60)),
                ("current_address", models.TextField(blank=True)),
                ("current_occupation", models.CharField(blank=True, max_length=60)),
                (
                    "net_income",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Net Income per month"
                    ),
                ),
                ("stable_income_available", models.BooleanField(default=False)),
                ("guarantee_available", models.BooleanField(default=False)),
                ("clean_schufa_report", models.BooleanField(default=False)),
                ("references_available", models.BooleanField(default=False)),
                ("long_term_leasing_desire", models.BooleanField(default=True)),
                ("quiet_and_tidy_tenant", models.BooleanField(default=True)),
                ("pets", models.BooleanField(default=False)),
                ("type_of_pets", models.CharField(blank=True, max_length=60)),
                (
                    "no_of_people",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of People to move"
                    ),
                ),
                ("children", models.BooleanField(default=False)),
                (
                    "no_of_children",
                    models.IntegerField(default=0, verbose_name="No. of children"),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lazyuserprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LazyFlatApplication",
            fields=[
                (
                    "flat_application_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("flat_ad_link", models.URLField(max_length=300)),
                ("title", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.IntegerField(blank=True, null=True)),
                ("district", models.CharField(max_length=50)),
                ("kaltmiete", models.CharField(max_length=20)),
                ("apartment_size", models.CharField(max_length=20)),
                ("deposit", models.CharField(blank=True, max_length=20)),
                ("rooms", models.IntegerField(blank=True, null=True)),
                ("extra_costs", models.CharField(blank=True, max_length=20)),
                ("heating_costs", models.CharField(blank=True, max_length=100)),
                ("total_cost", models.CharField(max_length=20)),
                ("additional_notes", models.TextField(blank=True)),
                ("flat_application_letter", models.TextField(blank=True)),
                (
                    "landlord_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flat_applications.landlord",
                    ),
                ),
                (
                    "renter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flat_applications.lazyrenter",
                    ),
                ),
            ],
        ),
    ]
