# Generated by Django 5.0.1 on 2024-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flat_applications", "0009_alter_lazyflatapplication_postal_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyflatapplication",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
