# Generated by Django 5.0.1 on 2024-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flat_applications", "0010_alter_lazyflatapplication_additional_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyflatapplication",
            name="additional_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
