# Generated by Django 5.0.1 on 2024-02-14 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazyjobapplication",
            name="ai_settings",
        ),
    ]
