# Generated by Django 5.0.1 on 2024-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_applications",
            "0004_rename_company_address_company_company_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="job_title",
            field=models.CharField(max_length=250),
        ),
    ]
