# Generated by Django 5.0.1 on 2024-02-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0007_alter_lazyjobapplication_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job_applications.company",
            ),
        ),
    ]
