# Generated by Django 5.0.1 on 2024-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_applications",
            "0010_rename_add_link_lazyjobapplication_ad_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="to_highlight",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Anything to highlight apart from CV Info?",
            ),
        ),
    ]
