# Generated by Django 5.0.1 on 2024-03-01 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0010_alter_lazyjobapplication_company_id_and_more"),
        ("job_applications", "0012_alter_lazyjobapplication_company_id_and_more"),
    ]

    operations = []
