# Generated by Django 5.0.1 on 2024-03-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0013_merge_20240301_0921"),
        ("users", "0008_alter_lazyuserprofile_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job_applications.company",
            ),
        ),
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="profile_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lazyuserprofile",
            ),
        ),
        migrations.AlterField(
            model_name="lazyjobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("apply", "Need to apply"),
                    ("applied", "Applied"),
                    ("interview", "Interview"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                    ("offer", "Offer"),
                    ("hired", "Hired"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="apply",
                max_length=50,
            ),
        ),
    ]
