# Generated by Django 5.0.1 on 2024-02-07 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LazyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("username", models.CharField(max_length=60, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="signed up"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("Job Applications", "Job Applications"),
                            ("Flat Applications", "Flat Applications"),
                            ("Job&Flat Applications", "Job&Flat Applications"),
                        ],
                        default="Job&Flat Applications",
                        max_length=60,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
