# Generated by Django 5.0.1 on 2024-02-13 21:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazyuser",
            name="use_case",
        ),
        migrations.CreateModel(
            name="LazyUserProfile",
            fields=[
                ("lazy_user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("job", "Job Applications"),
                            ("flat", "Flat Applications"),
                            ("both", "Job&Flat Applications"),
                        ],
                        default="job",
                        max_length=60,
                    ),
                ),
                ("cv_file", models.FileField(blank=True, null=True, upload_to="cvs")),
                ("cv_text", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=60)),
                (
                    "availability",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 2, 13, 21, 7, 26, 723994, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Earliest Start Date",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
