# Generated by Django 5.0.1 on 2024-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazyuser",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="lazyuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
