# Generated by Django 5.0.1 on 2024-02-09 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_lazyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazyprofile",
            name="availability",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 9, 22, 40, 34, 697389, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Earliest Start Date",
            ),
        ),
        migrations.AddField(
            model_name="lazyprofile",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("job", "Job Applications"),
                    ("flat", "Flat Applications"),
                    ("both", "Job&Flat Applications"),
                ],
                default="job",
                max_length=60,
            ),
        ),
    ]
