# Generated by Django 5.0.1 on 2024-02-10 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_lazyuserprofile_delete_lazyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazyuserprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="lazyuserprofile",
            name="availability",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 10, 0, 26, 17, 302942, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Earliest Start Date",
            ),
        ),
    ]
