# Generated by Django 5.0.1 on 2024-02-13 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_lazyuserprofile_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazyuser",
            name="use_case",
        ),
        migrations.AlterField(
            model_name="lazyuserprofile",
            name="availability",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 13, 14, 32, 26, 372561, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Earliest Start Date",
            ),
        ),
    ]
